### ISSUE TITLE
[issue] OSX Is not supported

### ISSUE THREAD

**Issue by Vel-San** [Vel-San/killing-floor-docker#4]
ucc-bin or ucc-bin-real are compiled as Linux binaries in the first place -- Linux binaries do not properly run on OSX Unix.

Testing with Noah doesn't work either. To fix the issue, we might have to revert to changing the whole run-time process and keep the scripts running inside the docker, instead of 

```Dockerfile
ENTRYPOINT ["/bin/bash", "kf1_install.sh"]
```

The whole point of a docker image is to bypass the limitations of kernels/OS platforms 😄 

@jdbrowndev  What do you think?

We can use a Multi-stage docker to switch from the FROM steamCMD img to FROM Ubuntu I guess?

**Comment by Vel-San** [comment]
https://github.com/Vel-San/killing-floor-docker#read-before-proceeding

**Comment by jdbrowndev** [comment]
Sorry @Vel-San, just now saw this. I don't have an OSX device to reproduce the issue, but it looks like you've resolved it in the readme?

**Comment by Vel-San** [comment]
> Sorry @Vel-San, just now saw this. I don't have an OSX device to reproduce the issue, but it looks like you've resolved it in the readme?

Hey @jdbrowndev !
That's fine 😄 I've fixed the issue as it was related to Docker itself. As you mentioned, instructions are now in the README.

Several other critical fixes were included too.
